name: 🐞 Сообщение об ошибке
description: Сообщить об ошибке или неполадке, для выявления и устранения причины
title: "[Ошибка]:"
labels: ["баг", "пофиксить"]
assignees:
- NikWebit
body:
  - type: markdown
    attributes:
      value: |
        Спасибо, что нашли время заполнить этот отчет об ошибке или неполадке!
  - type: textarea
    id: what-happened
    attributes:
      label: Опишите суть проблемы
      description:  Чёткое подробное описание проблемы.
      placeholder: Что случилось?
      value: "Найдена проблемка"
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Как можно воспроизвести проблему
      description: Опишите подробно, каким образом можно воспроизвести ситуацию о которой сообщаете.
    validations:
      required: true
      render: shell
