name: 🐞 Баг-репорт
description: Сообщить об ошибке или неполадке, для срочного исправления со стороны разработчиков
title: "Баг или неполадка"
labels: ["баг", "пофиксить"]
assignees:
  - NikWebit
body:
  - type: markdown
    attributes:
      value: |
       Спасибо, что нашли время заполнить этот отчет об ошибке или неполадке!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
