name: "🐞 Сообщение об ошибке"
description: "Сообщить об ошибке или неполадке, для выявления и устранения причины"
title: "[Ошибка]"
labels: ["баг", "пофиксить"]
assignees:
- NikWebit
body:
- type: markdown
attributes:
value: |
"Спасибо, что нашли время заполнить этот отчет об ошибке или неполадке!"
- type: input
id: what
attributes:
label: Опишите суть проблемы
description: "Чёткое и краткое описание ошибки"
placeholder: В чём проблема?
validations:
required: true 
