name: 🐞 Баг-репорт
description: Сообщить об ошибке или неполадке, для скорейшего выявления и устранения причины
title: "[Баг]: "
labels: ["баг", "пофиксить"]
assignees:
  - NikWebit
body:
  - type: markdown
    attributes:
      value: |
        Спасибо, что нашли время заполнить этот отчет об ошибке или неполадке!
  - type: input
  id: contact
    attributes:
      label: Опишите суть проблемы
      description: Чёткое и краткое описание неполадки или бага
      placeholder: что случилось?
    validations:
      required: false
