name: 🐞 Сообщение об ошибке
description: "Сообщить об ошибке или неполадке, для выявления и устранения причины"
title: "[Ошибка]"
labels: ["баг", "пофиксить"]
assignees:
  - NikWebit
body:
  - type: markdown
    attributes:
      value: |
       Спасибо, что нашли время заполнить этот отчет об ошибке или неполадке!
   - type: input
    id: what
    attributes:
      label: Опишите суть проблемы
      description: "Чёткое и краткое описание ошибки"
      placeholder: В чём проблема?
    validations:
      required: true     
  - type: input
    id: contact
    attributes:
      label: Контактная информация
      description: "Как можно с вами связаться в случае необходимости?"
      placeholder: email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: "Also tell us, what did you expect to happen?"
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
