name: 🐞 Баг-репорт
description: Сообщить об ошибке или неполадке, для скорейшего выявления и устранения причины
title: "[Баг]: "
labels: ["баг", "пофиксить"]
assignees:
  - NikWebit
body:
  - type: markdown
    attributes:
      value: |
        Спасибо, что нашли время заполнить этот отчет об ошибке или неполадке!
