name: 🐞 Баг-репорт
description: Сообщить об ошибке или неполадке, для срочного исправления со стороны разработчиков
title: "Баг или неполадка"
labels: [баг, пофиксить]
assignees:
- NikWebit
body:
- type: input 
attributes:
label: Опишите суть проблемы 
description: Чёткое и краткое описание неполадки или бага. 
validations:
required: true
